let wilayasAlgeries = [
  { Code: 1, Libelle: 'ادرار' },
  { Code: 2, Libelle: 'الشلف' },
  { Code: 3, Libelle: 'الاغواط' },
  { Code: 4, Libelle: 'ام البوافي' },
  { Code: 5, Libelle: 'باتنة' },
  { Code: 6, Libelle: 'بجاية' },
  { Code: 7, Libelle: 'بسكرة' },
  { Code: 8, Libelle: 'بشار' },
  { Code: 9, Libelle: 'بليده' },
  { Code: 10, Libelle: 'بويرة' },
  { Code: 11, Libelle: 'تمنراست' },
  { Code: 12, Libelle: 'تسية' },
  { Code: 13, Libelle: 'تلمسان' },
  { Code: 14, Libelle: 'تيارت' },
  { Code: 15, Libelle: 'تيزي وزو' },
  { Code: 16, Libelle: 'الجزائر' },
  { Code: 17, Libelle: 'الجلفة' },
  { Code: 18, Libelle: 'جيجل' },
  { Code: 19, Libelle: 'سطيف' },
  { Code: 20, Libelle: 'سعيدة' },
  { Code: 21, Libelle: 'سكسكدة' },
  { Code: 22, Libelle: 'سيدي بلعباس' },
  { Code: 23, Libelle: 'عنابة' },
  { Code: 24, Libelle: 'قالمة' },
  { Code: 25, Libelle: 'قسنطينة' },
  { Code: 26, Libelle: 'المدية' },
  { Code: 27, Libelle: 'مستغانم' },
  { Code: 28, Libelle: 'المسيلة' },
  { Code: 29, Libelle: 'معسكر' },
  { Code: 30, Libelle: 'ورقلة' },
  { Code: 31, Libelle: 'وهران' },
  { Code: 32, Libelle: 'البيض' },
  { Code: 33, Libelle: 'ايليزي' },
  { Code: 34, Libelle: 'برج بعريريج' },
  { Code: 35, Libelle: 'بومرداس' },
  { Code: 36, Libelle: 'الطارف' },
  { Code: 37, Libelle: 'تندوف' },
  { Code: 38, Libelle: 'تسمسيلت' },
  { Code: 39, Libelle: 'الوادي' },
  { Code: 40, Libelle: 'خنشلة' },
  { Code: 41, Libelle: 'سوق اهراس' },
  { Code: 42, Libelle: 'تيبازه' },
  { Code: 43, Libelle: 'ميله' },
  { Code: 44, Libelle: 'عين الدفلة' },
  { Code: 45, Libelle: 'نعامة' },
  { Code: 46, Libelle: 'عين تموشنت' },
  { Code: 47, Libelle: 'غرداية' },
  { Code: 48, Libelle: 'غيليزان' },
  { Code: 49, Libelle: 'تيميمون' },
  { Code: 50, Libelle: 'برج باجي مختار' },
  { Code: 51, Libelle: 'اولاد جلال' },
  { Code: 52, Libelle: 'بني عباس' },
  { Code: 53, Libelle: 'عين صالح' },
  { Code: 54, Libelle: 'عين قزام' },
  { Code: 55, Libelle: 'توقورت' },
  { Code: 56, Libelle: 'جانت' },
  { Code: 57, Libelle: 'المغير' },
  { Code: 58, Libelle: 'المنيعة' },
];
